//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Prefabs/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Infrastructure.InputService
{
    public partial class @GameInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GameInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""DefaultContext"",
            ""id"": ""9afaa9a1-b744-40a0-8ecd-62ea94ee2db0"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""9d97ba72-1278-4c9c-834c-5a65db1fa2b9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a26b06af-de7b-4fdd-9870-103021cd60ad"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""0349bd8b-27e2-4454-9a76-bfebe544e2d4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""248ed304-782e-4624-b593-eeeb658d6bdd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f8ae0d3c-3fe3-4f82-96dc-b7e6d0b4fc03"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7191aed2-0012-4413-9572-4b59b48187a7"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c70439d6-3ec8-4566-8233-72adab30bb75"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5be7c45e-6ae4-4edd-bf49-b097b78dd668"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6b07e6e0-0f89-451a-8aaa-66ab655a0b47"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f7738e4d-3d59-4fd8-a369-59dd03f36aea"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8150bace-083c-4abf-821f-2a9aa8263b1e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7b3ffc77-7ee2-4d44-8df8-6bddad4809d2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""782c0b2c-7cfd-4dc9-afcb-f179905ecebd"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54eaf279-2298-437f-be48-b7c9fce93c91"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7552fe30-f20c-4102-8775-ca972579ce18"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ffb95ef-23f2-48b7-a7ff-d840b7d35107"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DialogContext"",
            ""id"": ""18ead793-4192-4ca1-aeda-68dadb07a9fa"",
            ""actions"": [
                {
                    ""name"": ""Next"",
                    ""type"": ""Button"",
                    ""id"": ""906d12a8-9380-4a39-a1f2-a7ac6f02758f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1c2c659b-daa8-4651-a69c-c6ac44ef5137"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d552764-d953-4632-a6b8-dc631ece649b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // DefaultContext
            m_DefaultContext = asset.FindActionMap("DefaultContext", throwIfNotFound: true);
            m_DefaultContext_Look = m_DefaultContext.FindAction("Look", throwIfNotFound: true);
            m_DefaultContext_Move = m_DefaultContext.FindAction("Move", throwIfNotFound: true);
            m_DefaultContext_Interact = m_DefaultContext.FindAction("Interact", throwIfNotFound: true);
            m_DefaultContext_Jump = m_DefaultContext.FindAction("Jump", throwIfNotFound: true);
            // DialogContext
            m_DialogContext = asset.FindActionMap("DialogContext", throwIfNotFound: true);
            m_DialogContext_Next = m_DialogContext.FindAction("Next", throwIfNotFound: true);
        }

        ~@GameInput()
        {
            UnityEngine.Debug.Assert(!m_DefaultContext.enabled, "This will cause a leak and performance issues, GameInput.DefaultContext.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_DialogContext.enabled, "This will cause a leak and performance issues, GameInput.DialogContext.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // DefaultContext
        private readonly InputActionMap m_DefaultContext;
        private List<IDefaultContextActions> m_DefaultContextActionsCallbackInterfaces = new List<IDefaultContextActions>();
        private readonly InputAction m_DefaultContext_Look;
        private readonly InputAction m_DefaultContext_Move;
        private readonly InputAction m_DefaultContext_Interact;
        private readonly InputAction m_DefaultContext_Jump;
        public struct DefaultContextActions
        {
            private @GameInput m_Wrapper;
            public DefaultContextActions(@GameInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Look => m_Wrapper.m_DefaultContext_Look;
            public InputAction @Move => m_Wrapper.m_DefaultContext_Move;
            public InputAction @Interact => m_Wrapper.m_DefaultContext_Interact;
            public InputAction @Jump => m_Wrapper.m_DefaultContext_Jump;
            public InputActionMap Get() { return m_Wrapper.m_DefaultContext; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(DefaultContextActions set) { return set.Get(); }
            public void AddCallbacks(IDefaultContextActions instance)
            {
                if (instance == null || m_Wrapper.m_DefaultContextActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_DefaultContextActionsCallbackInterfaces.Add(instance);
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }

            private void UnregisterCallbacks(IDefaultContextActions instance)
            {
                @Look.started -= instance.OnLook;
                @Look.performed -= instance.OnLook;
                @Look.canceled -= instance.OnLook;
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Interact.started -= instance.OnInteract;
                @Interact.performed -= instance.OnInteract;
                @Interact.canceled -= instance.OnInteract;
                @Jump.started -= instance.OnJump;
                @Jump.performed -= instance.OnJump;
                @Jump.canceled -= instance.OnJump;
            }

            public void RemoveCallbacks(IDefaultContextActions instance)
            {
                if (m_Wrapper.m_DefaultContextActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IDefaultContextActions instance)
            {
                foreach (var item in m_Wrapper.m_DefaultContextActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_DefaultContextActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public DefaultContextActions @DefaultContext => new DefaultContextActions(this);

        // DialogContext
        private readonly InputActionMap m_DialogContext;
        private List<IDialogContextActions> m_DialogContextActionsCallbackInterfaces = new List<IDialogContextActions>();
        private readonly InputAction m_DialogContext_Next;
        public struct DialogContextActions
        {
            private @GameInput m_Wrapper;
            public DialogContextActions(@GameInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Next => m_Wrapper.m_DialogContext_Next;
            public InputActionMap Get() { return m_Wrapper.m_DialogContext; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(DialogContextActions set) { return set.Get(); }
            public void AddCallbacks(IDialogContextActions instance)
            {
                if (instance == null || m_Wrapper.m_DialogContextActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_DialogContextActionsCallbackInterfaces.Add(instance);
                @Next.started += instance.OnNext;
                @Next.performed += instance.OnNext;
                @Next.canceled += instance.OnNext;
            }

            private void UnregisterCallbacks(IDialogContextActions instance)
            {
                @Next.started -= instance.OnNext;
                @Next.performed -= instance.OnNext;
                @Next.canceled -= instance.OnNext;
            }

            public void RemoveCallbacks(IDialogContextActions instance)
            {
                if (m_Wrapper.m_DialogContextActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IDialogContextActions instance)
            {
                foreach (var item in m_Wrapper.m_DialogContextActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_DialogContextActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public DialogContextActions @DialogContext => new DialogContextActions(this);
        public interface IDefaultContextActions
        {
            void OnLook(InputAction.CallbackContext context);
            void OnMove(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
        }
        public interface IDialogContextActions
        {
            void OnNext(InputAction.CallbackContext context);
        }
    }
}
